# Generated by Django 6.1.1 on 2026-09-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('doxing', 'Doxing'), ('cyberstalking', 'Cyber Stalking'), ('cyberbullying', 'Cyber Bullying'), ('non_consensual', 'Non-Consensual Image Sharing'), ('other', 'Other')], max_length=50)),
                ('platform', models.CharField(help_text='Where did this occur? (e.g., WhatsApp, X, Facebook)', max_length=100)),
                ('description', models.TextField()),
                ('contact_info', models.CharField(blank=True, help_text='Optional: Leave blank to remain anonymous', max_length=255, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
